it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskTypeListView,
    PositionListView,
    WorkerListView,
    TaskListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    WorkerUpdateView,
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskDetailView,
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamUpdateView,
    TeamDeleteView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeDeleteView,
    TaskTypeUpdateView,
    TaskTypeCreateView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCompletedView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/completed/",
        TaskCompletedView.as_view(),
        name="task-completed"
    ),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),
]

app_name = "task_manager"

templates/includes/block_tasks.html
  <div class="card-group">
    <div class="card">
      <div class="card-header"
           style="background-color:orange; text-align: center">
        <h4>High Priority</h4>
      </div>
      {% if high_priority %}
        {% for task in high_priority %}
          {% include "includes/task_card.html" %}
        {% endfor %}
      {% else %}
        <div style="text-align: center">You do not have HIGH priority tasks yet..</div>
      {% endif %}
    </div>
    <div class="card">
      <div class="card-header"
           style="background-color:#FFD700; text-align: center">
        <h4>Medium Priority</h4>
      </div>
      {% if medium_priority %}
        {% for task in medium_priority %}
          {% include "includes/task_card.html" %}
        {% endfor %}
      {% else %}
          <div style="text-align: center">You do not have MEDIUM priority tasks yet..</div>
      {% endif %}
    </div>
    <div class="card">
      <div class="card-header"
           style="background-color:#ADFF2F; text-align: center">
        <h4>Low Priority</h4>
      </div>
      {% if low_priority %}
        {% for task in low_priority %}
          {% include "includes/task_card.html" %}
        {% endfor %}
      {% else %}
        <div style="text-align: center">You do not have LOW priority tasks yet..</div>
      {% endif %}
    </div>
    <div class="card">
      <div class="card-header"
           style="background-color:#9ACD32; text-align: center">
        <h4>DONE</h4>
      </div>
      {% if completed %}
        {% for task in completed %}
          {% include "includes/task_card.html" %}
        {% endfor %}
      {% else %}
        <div style="text-align: center">You do not have COMPLETED tasks yet..</div>
      {% endif %}
    </div>
    <div class="card">
      <div class="card-header" 
           style="background-color:#FF4500; text-align: center">
        <h4>FAILED</h4>
      </div>
      {% if failed %}
        {% for task in failed %}
          {% include "includes/task_card.html" %}
        {% endfor %}
      {% else %}
        <div style="text-align: center">You do not have FAILED tasks yet..</div>
      {% endif %}
    </div>
  </div>

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">IT Company Task Manager</h6>
          </div>
          <div>
            <h6 class="mt-3 mb-2 opacity-8">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="#" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Illustrations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Bits & Snippets
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Affiliate Program
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#r" target="_blank">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" target="_blank">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
{#        <div class="col-12">#}
{#          <div class="text-center">#}
{#            <p class="my-4 text-sm">#}
{#              Soft UI Design System by &copy; <a target="_blank" href="#" target="_blank">Creative Tim</a> #}
{#              - Coded by <a target="_blank" href="https://appseed.us" target="_blank">AppSeed</a>.#}
{#            </p>#}
{#          </div>#}
{#        </div>#}
      </div>
    </div>
  </footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              IT Company Task Manager
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="https://github.com/AndreiVed/it-company-task-manager" target="_blank">
                    <i class="fa fa-github me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}"> << </a>
        </li>
      {% endif %}
      <li class="page_item"><a
        class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</a></li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}"> >> </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/pagination_round.html
{% load query_transform %}
{% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}"> << </a>
          </li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}"> >> </a>
          </li>
        {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
      <p></p>
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-secondary" type="submit">Logout</button>
      </form>
    </li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'task_manager:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:worker-list' %}">All Workers</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:task-list' %}">All Tasks</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:project-list' %}">All Projects</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:team-list' %}">All Teams</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:task-type-list' %}">All Task Types</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:position-list' %}">All Positions</a></li>
  
</ul>

templates/includes/task_card.html
<div class="card-body border">
  <h5 class="card-title"><a href="{{ task.get_absolute_url }}" class="card-link">{{ task.name }}</a></h5>
  <h6 class="card-title"><a href="{{ task.project.get_absolute_url }}">{{ task.project.name }}</a></h6>
  <h6 class="card-subtitle mb-2 text-muted">type: {{ task.task_type }}</h6>
  <h6 class="card-subtitle mb-2 text-muted">created at: {{ task.created_date.date }}</h6>
  <h6 class="card-subtitle mb-2">deadline: {{ task.deadline }}</h6>          
  <p class="card-text" 
     style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
    {{ task.description }}
  </p>
</div>
<div class="card-footer border-0" ></div>