it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskTypeListView,
    PositionListView,
    WorkerListView,
    TaskListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    WorkerUpdateView,
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskDetailView,
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamUpdateView,
    TeamDeleteView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeDeleteView,
    TaskTypeUpdateView,
    TaskTypeCreateView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCompletedView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/completed/",
        TaskCompletedView.as_view(),
        name="task-completed"
    ),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=68, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=68, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("task_manager:project-detail", kwargs={"pk": self.pk})


class Team(models.Model):
    name = models.CharField(max_length=68, unique=True)
    projects = models.ManyToManyField(Project, related_name="teams")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="workers"
    )
    team = models.ForeignKey(
        Team,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="workers"
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"
        ordering = ["team", "username"]

    def __str__(self):
        return (f"{self.username} "
                f"({self.first_name} {self.last_name}) "
                f"- position: {self.position} - team: {self.team}")

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=68, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    HIGH = 'high'
    MEDIUM = 'medium'
    LOW = 'low'

    PRIORITY_CHOICES = [
        (HIGH, 'High Priority'),
        (MEDIUM, 'Medium Priority'),
        (LOW, 'Low Priority'),
    ]

    name = models.CharField(max_length=68, unique=True)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=68,
        choices=PRIORITY_CHOICES,
        default=MEDIUM
    )
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE,
        related_name="tasks"
    )
    assignees = models.ManyToManyField(Worker, related_name="tasks")
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="tasks",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["deadline"]

    def get_absolute_url(self):
        return reverse('task_manager:task-detail', kwargs={"pk": self.pk})

task_manager/forms.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError

from task_manager.models import Worker, Task


class WorkerCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
            "team",
        )


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = (
            "first_name",
            "last_name",
            "email",
            "position",
            "team",
        )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "search by username"
        })
    )


class ProjectSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "search by name of project"
        })
    )


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "priority",
            "deadline",
            "is_completed",
            "task_type",
            "project",
            "assignees",
        ]
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"}),
        }

    def clean_deadline(self):
        deadline = self.cleaned_data["deadline"]
        today = datetime.now().date()

        if deadline < today:
            raise ValidationError(
                "The deadline must be a date in the future."
            )

        return deadline


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "search by name of task"
        })
    )

task_manager/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    WorkerCreateForm,
    WorkerUpdateForm,
    WorkerSearchForm,
    ProjectSearchForm,
    TaskForm,
    TaskSearchForm
)

from task_manager.models import (
    Worker,
    Task,
    Project,
    Team,
    Position,
    TaskType,
)


# Create your views here.
@login_required
def index(request):
    """View function for the home page of the site."""

    num_workers = Worker.objects.count()
    num_tasks = Task.objects.count()
    num_projects = Project.objects.count()
    num_teams = Team.objects.count()
    num_positions = Position.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_projects": num_projects,
        "num_teams": num_teams,
        "num_positions": num_positions,
        "num_visits": num_visits + 1,
    }

    return render(request, "task_manager/index.html", context=context)


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", )
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.select_related("position")
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.all().prefetch_related("tasks")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task_manager:worker-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    queryset = Task.objects.all().select_related("task_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", )

        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        queryset = context["object_list"]
        context = handle_tasks_context_sorting(queryset, context)
        return context

    def get_queryset(self):
        queryset = Task.objects.select_related("task_type")
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            if name:
                queryset = queryset.filter(name__icontains=name)
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class TaskCompletedView(LoginRequiredMixin, generic.View):
    @staticmethod
    def post(request, pk):
        task = Task.objects.get(pk=pk)
        task.is_completed = True
        task.save()
        return redirect("task_manager:task-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "task_manager/task_type_list.html"
    context_object_name = "task_type_list"
    paginate_by = 5


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    template_name = "task_manager/task_type_form.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    template_name = "task_manager/task_type_form.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "task_manager/task_type_confirm_delete.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", )
        context["search_form"] = ProjectSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Project.objects.all()
        form = ProjectSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    queryset = Project.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.object.tasks.all()
        context = handle_tasks_context_sorting(queryset, context)
        return context


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    fields = "__all__"
    success_url = reverse_lazy("task_manager:project-list")


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    fields = "__all__"
    success_url = reverse_lazy("task_manager:project-list")


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy("task_manager:project-list")


class TeamListView(LoginRequiredMixin, generic.ListView):
    model = Team
    paginate_by = 5


class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    model = Team
    queryset = Team.objects.all()


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    fields = "__all__"
    success_url = reverse_lazy("task_manager:team-list")


class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    fields = "__all__"
    success_url = reverse_lazy("task_manager:team-list")


class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Team
    success_url = reverse_lazy("task_manager:team-list")


def handle_tasks_context_sorting(queryset, context):
    day_now = datetime.now().date()
    failed_tasks = queryset.filter(deadline__lt=day_now, is_completed=False)
    completed_tasks = queryset.filter(is_completed=True)

    in_process_tasks = queryset.exclude(
        id__in=failed_tasks.values_list("id", flat=True)
    ).exclude(id__in=completed_tasks.values_list("id", flat=True))

    context["completed"] = completed_tasks
    context["failed"] = failed_tasks
    context["high_priority"] = in_process_tasks.filter(priority=Task.HIGH)
    context["medium_priority"] = in_process_tasks.filter(priority=Task.MEDIUM)
    context["low_priority"] = in_process_tasks.filter(priority=Task.LOW)
    return context

templates/task_manager/project_detail.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %} About US {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} about-us {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}

  <!-- End Navbar -->
  <!-- -------- START HEADER 7 w/ text and video ------- -->
  <header class="bg-gradient-dark">
    <div class="page-header section-height-50" style="background-image: url('/static/assets/img/office-dark.jpg');">
      <span class="mask bg-gradient-info opacity-8"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">{{ project.name }}</h1>

            {% if project.teams %}
              <h5 class="text-white">TEAMS:</h5>
              {% for team in project.teams.all %}
                <h6 class="text-white">
                  <a href="{% url 'task_manager:team-detail' pk=team.id %}">
                  {{ team.name }}
                </h6>
              {% endfor %}
            {% endif %}
            <br>
            <button type="submit" class="btn bg-white text-dark">
              <a href="{% url 'task_manager:project-update' pk=project.id %}">
                Update project
              </a>
            </button>
            <button type="submit" class="btn bg-white text-dark">
              <a href="{% url 'task_manager:project-delete' pk=project.id %}">
                Delete project
              </a>
            </button>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1" />
          </g>
        </svg>
      </div>
    </div>
  </header>

  <div class="container">
    {% include "includes/block_tasks.html" %}
    <br>
  </div>
{% endblock %}

templates/task_manager/project_list.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %} About US {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include "includes/navigation.html" %}

  <!-- End Navbar -->
  <!-- -------- START HEADER 7 w/ text and video ------- -->
  <header class="bg-gradient-dark">
    <div class="page-header section-height-50" style="background-image: url('/static/assets/img/office-dark.jpg');">
      <span class="mask bg-gradient-info opacity-8"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Projects</h1>
            <br>
            <button type="submit" class="btn bg-white text-dark">
              <a href="{% url 'task_manager:project-create' %}">
                Create project
              </a>
            </button>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  
  <div class="container">
    <div class="row row-cols-1 row-cols-md-1 g-2">
      {% if project_list %}
        {% for project in project_list %}
          <div class="col">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">
                  <a href="{% url 'task_manager:project-detail' pk=project.id %}"> 
                    {{ project.name }}
                  </a>
                </h5>
                <p class="card-text">Count of teams in the project: {{ project.teams.count }} </p>
                <p class="card-text">Count of tasks: {{ project.tasks.count }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        {% else %}
          <p>There are no projects in the service.</p>
      {% endif %}
    </div>
    <br>
  </div>
{% endblock %}

templates/task_manager/task_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Task {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}
  <section class="py-sm-7 py-5 position-relative ">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto">
          <div class="row py-lg-7 py-5">
            <div class="card" style="width: 50rem;">
              <div class="card-body">
                <h4 class="card-title">{{ task.name }}</h4>
                <h6 class="card-title"><a href="{{ task.project.get_absolute_url }}">{{ task.project.name }}</a></h6>
                <h6 class="card-subtitle mb-2 text-muted">type: {{ task.task_type }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">created at: {{ task.created_date.date }}</h6>
                <h6 class="card-subtitle mb-2">deadline: {{ task.deadline }}</h6>          
                <p class="card-text">
                  {{ task.description }}
                </p>
                <p><strong>Assignees:</strong></p>
                <ul>
                  {% for worker in task.assignees.all %} 
                    <li>
                      {{ worker.position }}:
                      <a href="{{ worker.get_absolute_url }}">
                         {{ worker.first_name }} {{ worker.last_name }}  
                      </a> ;
                      Team:
                      <a href="{% url 'task_manager:team-detail' pk=worker.team.id %}">
                        ({{ worker.team.name }})
                      </a>
                    </li>
                  {% endfor %}
                </ul>
                {% if not task.is_completed %}
                  <form method="post" action="{% url 'task_manager:task-completed' pk=task.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">
                      Mark as DONE
                    </button>
                  </form>
                {% endif %}
                <a href="{% url 'task_manager:task-update' pk=task.id %}" class="btn btn-primary link-to-page">
                  Update
                </a>
                <a href="{% url 'task_manager:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
                  Delete
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Worker {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include "includes/navigation.html" %}

  <section class="py-sm-7 py-5 position-relative ">
    <div class="container">
      <div class="row">
        <div class="col-10 mx-auto">
          <div class="row py-lg-7 py-5">

            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ worker.first_name }} {{ worker.last_name }}</h4>

              </div>
              <p class="text-lg mb-0">
                <p>{{ worker.position }}</p>
                <p><strong>Username:</strong> {{ worker.username }}</p>
                <p><strong>Email:</strong> {{ worker.email }}</p>
                <p><strong>Team:</strong> {{ worker.team }}</p>
                <br>
                <a href="{% url 'task_manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
                  Update
                </a>
                <a href="{% url 'task_manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
                  Delete
                </a>
              </p>
            </div>
              <div class="container">
                <div class="row row-cols-1 row-cols-md-1 g-2">
                  <p><strong>Tasks:</strong></p>
                  {% if worker.tasks %}
                    {% for task in worker.tasks.all %}          
                      <div class="col">
                        <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">
                              <a href="{% url 'task_manager:task-detail' pk=task.id %}"> 
                                {{ task.name }}
                              </a>
                            </h5>
                            <p><strong>Project:</strong> {{ task.project.name }}</p>
                            <p><strong>Description:</strong> {{ task.description }}</p>
                            <p class="text-muted"><strong>Id:</strong> {{task.id}}</p>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                    {% else %}
                      <p>There are no tasks yet.</p>
                  {% endif %}
                </div>
                <br>
              </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}